apiVersion: v1
kind: ConfigMap
metadata:
  namespace: test-ccdj
  name: envs-production-django
data:
  DJANGO_SETTINGS_MODULE: "config.settings.production"
  DJANGO_ADMIN_URL: "nxB0AWFHi204T2g7VxhVxJ5UYKMBQIjl/"
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_SECURE_SSL_REDIRECT: "no"
  DJANGO_ACCOUNT_ALLOW_REGISTRATION: "no"
  WEB_CONCURRENCY: "4"
  # REDIS_URL: "redis://redis:6379/0"
  CELERY_FLOWER_USER: debug
  # REDIS_URL: "rediss://default:AVNS_9ZcQQxUCrLaSY41kwB1@private-db-redis-nyc3-67768-do-user-10228058-0.b.db.ondigitalocean.com:25061/0"
  REDIS_URL: "rediss://default:AVNS_9ZcQQxUCrLaSY41kwB1@private-db-redis-nyc3-67768-do-user-10228058-0.b.db.ondigitalocean.com:25061/0"
  CELERY_BROKER_URL: "rediss://default:AVNS_9ZcQQxUCrLaSY41kwB1@private-db-redis-nyc3-67768-do-user-10228058-0.b.db.ondigitalocean.com:25061/0"
  # CELERY_BROKER_URL: "rediss://default:AVNS_9ZcQQxUCrLaSY41kwB1@private-db-redis-nyc3-67768-do-user-10228058-0.b.db.ondigitalocean.com:25061/0?ssl_cert_reqs=CERT_NONE"
  # REDIS_URL: "redis://default:AVNS_9ZcQQxUCrLaSY41kwB1@private-db-redis-nyc3-67768-do-user-10228058-0.b.db.ondigitalocean.com:25061"
  # REDIS_URL: "redis://default:AVNS_9ZcQQxUCrLaSY41kwB1@db-redis-nyc3-67768-do-user-10228058-0.b.db.ondigitalocean.com:25061"
  # REDIS_URL: "rediss://default:AVNS_6h6MB2S6N3DQu2r3Ezo@db-redis-nyc1-13574-do-user-10228058-0.b.db.ondigitalocean.com:25061"
