apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-django-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: dev.ikigaidojo.io
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: django
            port:
              number: 5000
